// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Statistics.Server.Models;

namespace Statistics.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190823030002_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Statistics.Shared.AbsWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AbsType");

                    b.Property<string>("DayOfWeek");

                    b.Property<string>("Evaluation");

                    b.Property<DateTime>("SubmitDate");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("AbsWorkouts");
                });

            modelBuilder.Entity("Statistics.Shared.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("Number");

                    b.Property<string>("Repetitions");

                    b.Property<string>("ShouldAddWeight");

                    b.Property<int>("UserId");

                    b.Property<string>("Weight");

                    b.Property<int?>("WorkoutId");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Statistics.Shared.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DayOfWeek");

                    b.Property<string>("Evaluation");

                    b.Property<string>("Phase");

                    b.Property<DateTime>("SubmitDate");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Statistics.Shared.Exercise", b =>
                {
                    b.HasOne("Statistics.Shared.Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId");
                });
#pragma warning restore 612, 618
        }
    }
}
